// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRF5OtBO7JX4XRwOGE5uBgL4lJXCGMXvw',
    appId: '1:605774815836:web:d278abec71b696d36afc99',
    messagingSenderId: '605774815836',
    projectId: 'brew-crew-e91ed',
    authDomain: 'brew-crew-e91ed.firebaseapp.com',
    storageBucket: 'brew-crew-e91ed.appspot.com',
    measurementId: 'G-XC5EBPR2QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCIPbjWu4BmkBN2f5txx8i_5hELANmDug',
    appId: '1:605774815836:android:1614773f4950b50b6afc99',
    messagingSenderId: '605774815836',
    projectId: 'brew-crew-e91ed',
    storageBucket: 'brew-crew-e91ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvCwmt06Fz6Nb1ETNeRDCTal16yfmdX-I',
    appId: '1:605774815836:ios:bc25c8f88eb1be476afc99',
    messagingSenderId: '605774815836',
    projectId: 'brew-crew-e91ed',
    storageBucket: 'brew-crew-e91ed.appspot.com',
    iosClientId: '605774815836-phqm4irj71mj8bgflm6bsv1ve7ofsc4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.crewBrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvCwmt06Fz6Nb1ETNeRDCTal16yfmdX-I',
    appId: '1:605774815836:ios:bc25c8f88eb1be476afc99',
    messagingSenderId: '605774815836',
    projectId: 'brew-crew-e91ed',
    storageBucket: 'brew-crew-e91ed.appspot.com',
    iosClientId: '605774815836-phqm4irj71mj8bgflm6bsv1ve7ofsc4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.crewBrew',
  );
}
